image: maven:3.8

jlink:
  script:
    - "mvn javafx:jlink -B"

  artifacts:
    paths:
      - "target/*.zip"


fatjar:
  script:
    - "mvn package -B"
  artifacts:
    paths:
      - "target/*.jar"
