image: maven:3.8

jlink:
  script:
    - echo "Buildím jlink."
    - "mvn javafx:jlink -B"
  artifacts:
    paths:
      - "target/*.zip"


fatjar:
  script:
    - echo "Buildím fat jar."
    - "mvn package -B"
  artifacts:
    paths:
      - "target/*.jar"
